apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sfx-config
    

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: es
spec:
  selector:
    matchLabels:
      app: es
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
      - env:
        - name: discovery.type
          value: single-node
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        imagePullPolicy: ""
        name: es
        ports:
        - containerPort: 9200
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: esdata1
      restartPolicy: Always
      volumes:
      - name: esdata1


---
apiVersion: v1
kind: Service
metadata:
  name: es
spec:
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  selector:
    app: es

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
spec:
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
      - image: locustio/locust
        command: [ "/bin/sh", "-c", "ls /mnt/locust", "-f locustfile.py --headless -H http://localhost:5000 -u 10 -r 1"]
        imagePullPolicy: ""
        name: locust
        ports:
        - containerPort: 8089
        resources: {}
        volumeMounts:
        - name: locust-volume
          mountPath: /mnt/locust
      volumes:
        - name: locust-volume
          configMap:
            name: locust-config

---
apiVersion: v1
kind: Service
metadata:
  name: locust
spec:
  ports:
  - name: locust
    port: 8089
    targetPort: 8089
  selector:
    app: locust


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfx-agent
spec:
  selector:
    matchLabels:
      app: sfx-agent
  template:
    metadata:
      labels:
        app: sfx-agent
    spec:
      containers:
      - image: quay.io/signalfx/signalfx-agent:5
        imagePullPolicy: ""
        name: sfx-agent
        ports:
        - containerPort: 9080
        resources: {}
        volumeMounts:
        - name: sfx-volume
          mountPath: /etc/signalfx
      volumes:
        - name: sfx-volume
          configMap:
            name: sfx-config


---
apiVersion: v1
kind: Service
metadata:
  name: sfx-agent
spec:
  ports:
  - name: sfx-agent
    port: 9080
    targetPort: 9080
  selector:
    app: sfx-agent


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - args:
        - sfx-py-trace
        - app.py
        env:
        - name: DEBUG
          value: "True"
        - name: SIGNALFX_SERVICE_NAME
          value: "FoodTruck_Linda"
        image: daz2.jfrog.io/daz-srelabs/foodtruck-web:1.0.0
        imagePullPolicy: Always
        name: foodtruck
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
      - name: foodtrucksecret1

---

apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - name: web
    port: 5000
    targetPort: 5000
  selector:
    app: web
  type: LoadBalancer





